spring:
  application:
    name: datingapp
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/datingdb?authSource=admin

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  queue:
    capacity: 100





